name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'
      - 'default.mk'
      - 'Makefile'
      - '.github/workflows/release.yml'
  pull_request:
    branches:
      - master

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Build
        run: make build
      - name: Run Exporter
        run: ./bin/opcache_exporter -h
